# Generated by Django 4.0.6 on 2022-07-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_eee_teacher_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='userRegister',
        ),
    ]
